version: '3.8'

services:
  geoip:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geoip-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_KEY=${API_KEY}
      - LOG_LEVEL=info
      - GEOIP_CITY_DB=/app/geoip-bases/GeoLite2-City.mmdb
      - GEOIP_COUNTRY_DB=/app/geoip-bases/GeoLite2-Country.mmdb
      - GEOIP_ASN_DB=/app/geoip-bases/GeoLite2-ASN.mmdb
    volumes:
      - ./geoip-bases:/app/geoip-bases:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    user: "appuser:appgroup"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - geoip-network

networks:
  geoip-network:
    driver: bridge
